development:
  adapter: mysql
  encoding: utf8
  database: discussions_dev
  username: root
  password: ruby186

test:
  adapter: mysql
  encoding: utf8
  database: discussions_test
  username: root
  password: ruby186

production:
  adapter: mysql
  encoding: utf8
  database: discussions_prod
  username: root
  password: ruby186
